from __future__ import annotations

from typing import Protocol

from app.modules.identity.contracts import AuthUser


class IdentityRepository(Protocol):
    def get_user_by_email(self, email: str) -> AuthUser | None: ...

    def get_password_hash(self, user_id: int) -> str | None: ...

    def create_mfa_challenge(self, user_id: int) -> str: ...

    def consume_mfa_challenge(self, challenge_token: str) -> AuthUser | None: ...

    def get_mfa_secret(self, user_id: int) -> str | None: ...

    def create_session(self, user_id: int) -> tuple[str, str]: ...

    def create_step_up(self, user_id: int, purpose: str) -> tuple[str, str]: ...
