from app.firmware.models import BoardPreset


BOARD_PRESETS: dict[str, BoardPreset] = {
    "btt_octopus_pro_f446_usb_can": BoardPreset(
        id="btt_octopus_pro_f446_usb_can",
        vendor="BigTreeTech",
        name="BTT Octopus Pro STM32F446 USB-CAN bridge",
        mcu="stm32f446",
        architecture="stm32",
        connection_type="usb_can_bridge",
        communication="USB to CAN bus bridge",
        bootloader_offset="32KiB",
        canbus_pins="PD0/PD1",
        config_file="firmware/btt_octopus_pro_f446_usb_can.config",
        build_output="out/klipper.bin",
        default_flash_method="katapult_usb_can",
        notes="Preset inicial para Octopus/Octopus Pro F446 atuando como bridge USB-CAN.",
    ),
    "btt_octopus_v1_1_f446_usb_can": BoardPreset(
        id="btt_octopus_v1_1_f446_usb_can",
        vendor="BigTreeTech",
        name="BTT Octopus v1.1 STM32F446 USB-CAN bridge",
        mcu="stm32f446",
        architecture="stm32",
        connection_type="usb_can_bridge",
        communication="USB to CAN bus bridge",
        bootloader_offset="32KiB",
        canbus_pins="PD0/PD1",
        config_file="firmware/btt_octopus_v1_1_f446_usb_can.config",
        build_output="out/klipper.bin",
        default_flash_method="katapult_usb_can",
        notes="Preset comum para Voron 2.4 com Octopus F446 em bridge.",
    ),
    "btt_octopus_pro_h723_usb_can": BoardPreset(
        id="btt_octopus_pro_h723_usb_can",
        vendor="BigTreeTech",
        name="BTT Octopus Pro STM32H723 USB-CAN bridge",
        mcu="stm32h723",
        architecture="stm32",
        connection_type="usb_can_bridge",
        communication="USB to CAN bus bridge",
        bootloader_offset="128KiB",
        canbus_pins="PD0/PD1",
        config_file="firmware/btt_octopus_pro_h723_usb_can.config",
        build_output="out/klipper.bin",
        default_flash_method="katapult_usb_can",
        notes="Preset para variantes H723; validar bootloader e clock antes de build.",
    ),
    "btt_ebb36_g0b1_can": BoardPreset(
        id="btt_ebb36_g0b1_can",
        vendor="BigTreeTech",
        name="BTT EBB36 STM32G0B1 CAN",
        mcu="stm32g0b1",
        architecture="stm32",
        connection_type="can",
        communication="CAN bus",
        bootloader_offset="8KiB",
        canbus_pins="PB0/PB1",
        config_file="firmware/btt_ebb36_g0b1_can.config",
        build_output="out/klipper.bin",
        default_flash_method="katapult_can",
        notes="Preset comum para toolhead CAN EBB36 G0B1.",
    ),
    "btt_ebb42_g0b1_can": BoardPreset(
        id="btt_ebb42_g0b1_can",
        vendor="BigTreeTech",
        name="BTT EBB42 STM32G0B1 CAN",
        mcu="stm32g0b1",
        architecture="stm32",
        connection_type="can",
        communication="CAN bus",
        bootloader_offset="8KiB",
        canbus_pins="PB0/PB1",
        config_file="firmware/btt_ebb42_g0b1_can.config",
        build_output="out/klipper.bin",
        default_flash_method="katapult_can",
        notes="Preset comum para toolhead CAN EBB42 G0B1.",
    ),
    "btt_sb2209_rp2040_can": BoardPreset(
        id="btt_sb2209_rp2040_can",
        vendor="BigTreeTech",
        name="BTT SB2209 RP2040 CAN",
        mcu="rp2040",
        architecture="rp2040",
        connection_type="can",
        communication="CAN bus",
        bootloader_offset="none",
        canbus_pins=None,
        config_file="firmware/btt_sb2209_rp2040_can.config",
        build_output="out/klipper.uf2",
        default_flash_method="katapult_can",
        notes="Preset inicial; validar documentação da placa antes de build.",
    ),
    "btt_sb2240_rp2040_can": BoardPreset(
        id="btt_sb2240_rp2040_can",
        vendor="BigTreeTech",
        name="BTT SB2240 RP2040 CAN",
        mcu="rp2040",
        architecture="rp2040",
        connection_type="can",
        communication="CAN bus",
        bootloader_offset="none",
        canbus_pins=None,
        config_file="firmware/btt_sb2240_rp2040_can.config",
        build_output="out/klipper.uf2",
        default_flash_method="katapult_can",
        notes="Preset inicial; validar documentação da placa antes de build.",
    ),
    "btt_kraken_h723_usb_can": BoardPreset(
        id="btt_kraken_h723_usb_can",
        vendor="BigTreeTech",
        name="BTT Kraken STM32H723 USB-CAN bridge",
        mcu="stm32h723",
        architecture="stm32",
        connection_type="usb_can_bridge",
        communication="USB to CAN bus bridge",
        bootloader_offset="128KiB",
        canbus_pins="PD0/PD1",
        config_file="firmware/btt_kraken_h723_usb_can.config",
        build_output="out/klipper.bin",
        default_flash_method="katapult_usb_can",
        notes="Preset para Kraken H723 em bridge USB-CAN; validar clock e bootloader antes do build.",
    ),
    "btt_manta_m5p_g0b1_usb_can": BoardPreset(
        id="btt_manta_m5p_g0b1_usb_can",
        vendor="BigTreeTech",
        name="BTT Manta M5P STM32G0B1 USB-CAN bridge",
        mcu="stm32g0b1",
        architecture="stm32",
        connection_type="usb_can_bridge",
        communication="USB to CAN bus bridge",
        bootloader_offset="8KiB",
        canbus_pins="PB0/PB1",
        config_file="firmware/btt_manta_m5p_g0b1_usb_can.config",
        build_output="out/klipper.bin",
        default_flash_method="katapult_usb_can",
        notes="Preset para Manta M5P G0B1 em bridge USB-CAN.",
    ),
    "btt_manta_m8p_v2_h723_usb_can": BoardPreset(
        id="btt_manta_m8p_v2_h723_usb_can",
        vendor="BigTreeTech",
        name="BTT Manta M8P v2.0 STM32H723 USB-CAN bridge",
        mcu="stm32h723",
        architecture="stm32",
        connection_type="usb_can_bridge",
        communication="USB to CAN bus bridge",
        bootloader_offset="128KiB",
        canbus_pins="PD0/PD1",
        config_file="firmware/btt_manta_m8p_v2_h723_usb_can.config",
        build_output="out/klipper.bin",
        default_flash_method="katapult_usb_can",
        notes="Preset para Manta M8P v2.0 H723 em bridge USB-CAN.",
    ),
    "btt_skr_3_h743_usb_can": BoardPreset(
        id="btt_skr_3_h743_usb_can",
        vendor="BigTreeTech",
        name="BTT SKR-3 STM32H743 USB-CAN bridge",
        mcu="stm32h743",
        architecture="stm32",
        connection_type="usb_can_bridge",
        communication="USB to CAN bus bridge",
        bootloader_offset="128KiB",
        canbus_pins="PD0/PD1",
        config_file="firmware/btt_skr_3_h743_usb_can.config",
        build_output="out/klipper.bin",
        default_flash_method="katapult_usb_can",
        notes="Preset para SKR-3 H743; confirmar variante H743/H723 no chip fisico antes do build.",
    ),
    "mellow_fly_sht36_v2_g0b1_can": BoardPreset(
        id="mellow_fly_sht36_v2_g0b1_can",
        vendor="Mellow",
        name="Mellow Fly SHT36 v2 STM32G0B1 CAN",
        mcu="stm32g0b1",
        architecture="stm32",
        connection_type="can",
        communication="CAN bus",
        bootloader_offset="8KiB",
        canbus_pins="PB0/PB1",
        config_file="firmware/mellow_fly_sht36_v2_g0b1_can.config",
        build_output="out/klipper.bin",
        default_flash_method="katapult_can",
        notes="Preset inicial para toolhead CAN Mellow SHT36.",
    ),
    "mellow_fly_sb2040_rp2040_can": BoardPreset(
        id="mellow_fly_sb2040_rp2040_can",
        vendor="Mellow",
        name="Mellow Fly SB2040 RP2040 CAN",
        mcu="rp2040",
        architecture="rp2040",
        connection_type="can",
        communication="CAN bus",
        bootloader_offset="none",
        canbus_pins=None,
        config_file="firmware/mellow_fly_sb2040_rp2040_can.config",
        build_output="out/klipper.uf2",
        default_flash_method="katapult_can",
        notes="Preset inicial para toolhead CAN Mellow SB2040.",
    ),
    "mellow_fly_sb2040_v3_rp2040_can": BoardPreset(
        id="mellow_fly_sb2040_v3_rp2040_can",
        vendor="Mellow",
        name="Mellow Fly SB2040 v3 RP2040 CAN",
        mcu="rp2040",
        architecture="rp2040",
        connection_type="can",
        communication="CAN bus",
        bootloader_offset="none",
        canbus_pins=None,
        config_file="firmware/mellow_fly_sb2040_v3_rp2040_can.config",
        build_output="out/klipper.uf2",
        default_flash_method="katapult_can",
        notes="Preset para toolhead CAN Mellow SB2040 v3.",
    ),
    "mellow_fly_sht36_v3_rp2040_can": BoardPreset(
        id="mellow_fly_sht36_v3_rp2040_can",
        vendor="Mellow",
        name="Mellow Fly SHT36 v3 RP2040 CAN",
        mcu="rp2040",
        architecture="rp2040",
        connection_type="can",
        communication="CAN bus",
        bootloader_offset="none",
        canbus_pins=None,
        config_file="firmware/mellow_fly_sht36_v3_rp2040_can.config",
        build_output="out/klipper.uf2",
        default_flash_method="katapult_can",
        notes="Preset para toolhead CAN Mellow SHT36 v3.",
    ),
    "mellow_fly_super8_pro_h723_usb_can": BoardPreset(
        id="mellow_fly_super8_pro_h723_usb_can",
        vendor="Mellow",
        name="Mellow Fly-Super8 Pro H723 USB-CAN bridge",
        mcu="stm32h723",
        architecture="stm32",
        connection_type="usb_can_bridge",
        communication="USB to CAN bus bridge",
        bootloader_offset="128KiB",
        canbus_pins="PD0/PD1",
        config_file="firmware/mellow_fly_super8_pro_h723_usb_can.config",
        build_output="out/klipper.bin",
        default_flash_method="katapult_usb_can",
        notes="Preset para Fly-Super8 Pro H723 em bridge USB-CAN.",
    ),
    "fysetc_spider_f446_usb": BoardPreset(
        id="fysetc_spider_f446_usb",
        vendor="Fysetc",
        name="Fysetc Spider STM32F446 USB",
        mcu="stm32f446",
        architecture="stm32",
        connection_type="usb",
        communication="USB",
        bootloader_offset="32KiB",
        canbus_pins=None,
        config_file="firmware/fysetc_spider_f446_usb.config",
        build_output="out/klipper.bin",
        default_flash_method="dfu_usb",
        notes="Preset inicial para Spider F446 via USB.",
    ),
    "fysetc_spider_v2_2_f446_usb_can": BoardPreset(
        id="fysetc_spider_v2_2_f446_usb_can",
        vendor="Fysetc",
        name="Fysetc Spider v2.2 STM32F446 USB-CAN bridge",
        mcu="stm32f446",
        architecture="stm32",
        connection_type="usb_can_bridge",
        communication="USB to CAN bus bridge",
        bootloader_offset="32KiB",
        canbus_pins="PD0/PD1",
        config_file="firmware/fysetc_spider_v2_2_f446_usb_can.config",
        build_output="out/klipper.bin",
        default_flash_method="katapult_usb_can",
        notes="Preset para Spider v2.2 F446 em bridge USB-CAN.",
    ),
    "fysetc_spider_v2_3_f446_usb_can": BoardPreset(
        id="fysetc_spider_v2_3_f446_usb_can",
        vendor="Fysetc",
        name="Fysetc Spider v2.3 STM32F446 USB-CAN bridge",
        mcu="stm32f446",
        architecture="stm32",
        connection_type="usb_can_bridge",
        communication="USB to CAN bus bridge",
        bootloader_offset="32KiB",
        canbus_pins="PD0/PD1",
        config_file="firmware/fysetc_spider_v2_3_f446_usb_can.config",
        build_output="out/klipper.bin",
        default_flash_method="katapult_usb_can",
        notes="Preset para Spider v2.3 F446 em bridge USB-CAN.",
    ),
    "fysetc_spider_v3_h723_usb_can": BoardPreset(
        id="fysetc_spider_v3_h723_usb_can",
        vendor="Fysetc",
        name="Fysetc Spider v3.0 H7 STM32H723 USB-CAN bridge",
        mcu="stm32h723",
        architecture="stm32",
        connection_type="usb_can_bridge",
        communication="USB to CAN bus bridge",
        bootloader_offset="128KiB",
        canbus_pins="PD0/PD1",
        config_file="firmware/fysetc_spider_v3_h723_usb_can.config",
        build_output="out/klipper.bin",
        default_flash_method="katapult_usb_can",
        notes="Preset para Spider v3.0 H7 em bridge USB-CAN.",
    ),
    "fysetc_h36_g0b1_can": BoardPreset(
        id="fysetc_h36_g0b1_can",
        vendor="Fysetc",
        name="Fysetc H36 STM32G0B1 CAN",
        mcu="stm32g0b1",
        architecture="stm32",
        connection_type="can",
        communication="CAN bus",
        bootloader_offset="8KiB",
        canbus_pins="PB0/PB1",
        config_file="firmware/fysetc_h36_g0b1_can.config",
        build_output="out/klipper.bin",
        default_flash_method="katapult_can",
        notes="Preset para toolhead CAN Fysetc H36.",
    ),
    "fysetc_sb_combo_v2_f072_can": BoardPreset(
        id="fysetc_sb_combo_v2_f072_can",
        vendor="Fysetc",
        name="Fysetc SB Combo V2 STM32F072 CAN",
        mcu="stm32f072",
        architecture="stm32",
        connection_type="can",
        communication="CAN bus",
        bootloader_offset="8KiB",
        canbus_pins=None,
        config_file="firmware/fysetc_sb_combo_v2_f072_can.config",
        build_output="out/klipper.bin",
        default_flash_method="katapult_can",
        notes="Preset para toolhead CAN Fysetc SB Combo V2.",
    ),
    "fysetc_sb_can_g0b1": BoardPreset(
        id="fysetc_sb_can_g0b1",
        vendor="Fysetc",
        name="Fysetc SB CAN STM32G0B1",
        mcu="stm32g0b1",
        architecture="stm32",
        connection_type="can",
        communication="CAN bus",
        bootloader_offset="8KiB",
        canbus_pins="PB0/PB1",
        config_file="firmware/fysetc_sb_can_g0b1.config",
        build_output="out/klipper.bin",
        default_flash_method="katapult_can",
        notes="Preset inicial para toolhead CAN Fysetc.",
    ),
}
