from app.firmware.models import BoardPreset


BOARD_PRESETS: dict[str, BoardPreset] = {
    "btt_octopus_pro_f446_usb_can": BoardPreset(
        id="btt_octopus_pro_f446_usb_can",
        vendor="BigTreeTech",
        name="BTT Octopus Pro STM32F446 USB-CAN bridge",
        mcu="stm32f446",
        architecture="stm32",
        connection_type="usb_can_bridge",
        communication="USB to CAN bus bridge",
        bootloader_offset="32KiB",
        canbus_pins="PD0/PD1",
        build_output="out/klipper.bin",
        default_flash_method="katapult_usb_can",
        notes="Preset inicial para Octopus/Octopus Pro F446 atuando como bridge USB-CAN.",
    ),
    "btt_octopus_v1_1_f446_usb_can": BoardPreset(
        id="btt_octopus_v1_1_f446_usb_can",
        vendor="BigTreeTech",
        name="BTT Octopus v1.1 STM32F446 USB-CAN bridge",
        mcu="stm32f446",
        architecture="stm32",
        connection_type="usb_can_bridge",
        communication="USB to CAN bus bridge",
        bootloader_offset="32KiB",
        canbus_pins="PD0/PD1",
        build_output="out/klipper.bin",
        default_flash_method="katapult_usb_can",
        notes="Preset comum para Voron 2.4 com Octopus F446 em bridge.",
    ),
    "btt_octopus_pro_h723_usb_can": BoardPreset(
        id="btt_octopus_pro_h723_usb_can",
        vendor="BigTreeTech",
        name="BTT Octopus Pro STM32H723 USB-CAN bridge",
        mcu="stm32h723",
        architecture="stm32",
        connection_type="usb_can_bridge",
        communication="USB to CAN bus bridge",
        bootloader_offset="128KiB",
        canbus_pins="PD0/PD1",
        build_output="out/klipper.bin",
        default_flash_method="katapult_usb_can",
        notes="Preset para variantes H723; validar bootloader e clock antes de build.",
    ),
    "btt_ebb36_g0b1_can": BoardPreset(
        id="btt_ebb36_g0b1_can",
        vendor="BigTreeTech",
        name="BTT EBB36 STM32G0B1 CAN",
        mcu="stm32g0b1",
        architecture="stm32",
        connection_type="can",
        communication="CAN bus",
        bootloader_offset="8KiB",
        canbus_pins="PB0/PB1",
        build_output="out/klipper.bin",
        default_flash_method="katapult_can",
        notes="Preset comum para toolhead CAN EBB36 G0B1.",
    ),
    "btt_ebb42_g0b1_can": BoardPreset(
        id="btt_ebb42_g0b1_can",
        vendor="BigTreeTech",
        name="BTT EBB42 STM32G0B1 CAN",
        mcu="stm32g0b1",
        architecture="stm32",
        connection_type="can",
        communication="CAN bus",
        bootloader_offset="8KiB",
        canbus_pins="PB0/PB1",
        build_output="out/klipper.bin",
        default_flash_method="katapult_can",
        notes="Preset comum para toolhead CAN EBB42 G0B1.",
    ),
    "btt_sb2209_rp2040_can": BoardPreset(
        id="btt_sb2209_rp2040_can",
        vendor="BigTreeTech",
        name="BTT SB2209 RP2040 CAN",
        mcu="rp2040",
        architecture="rp2040",
        connection_type="can",
        communication="CAN bus",
        bootloader_offset="none",
        canbus_pins=None,
        build_output="out/klipper.uf2",
        default_flash_method="katapult_can",
        notes="Preset inicial; validar documentação da placa antes de build.",
    ),
    "btt_sb2240_rp2040_can": BoardPreset(
        id="btt_sb2240_rp2040_can",
        vendor="BigTreeTech",
        name="BTT SB2240 RP2040 CAN",
        mcu="rp2040",
        architecture="rp2040",
        connection_type="can",
        communication="CAN bus",
        bootloader_offset="none",
        canbus_pins=None,
        build_output="out/klipper.uf2",
        default_flash_method="katapult_can",
        notes="Preset inicial; validar documentação da placa antes de build.",
    ),
    "mellow_fly_sht36_v2_g0b1_can": BoardPreset(
        id="mellow_fly_sht36_v2_g0b1_can",
        vendor="Mellow",
        name="Mellow Fly SHT36 v2 STM32G0B1 CAN",
        mcu="stm32g0b1",
        architecture="stm32",
        connection_type="can",
        communication="CAN bus",
        bootloader_offset="8KiB",
        canbus_pins="PB0/PB1",
        build_output="out/klipper.bin",
        default_flash_method="katapult_can",
        notes="Preset inicial para toolhead CAN Mellow SHT36.",
    ),
    "mellow_fly_sb2040_rp2040_can": BoardPreset(
        id="mellow_fly_sb2040_rp2040_can",
        vendor="Mellow",
        name="Mellow Fly SB2040 RP2040 CAN",
        mcu="rp2040",
        architecture="rp2040",
        connection_type="can",
        communication="CAN bus",
        bootloader_offset="none",
        canbus_pins=None,
        build_output="out/klipper.uf2",
        default_flash_method="katapult_can",
        notes="Preset inicial para toolhead CAN Mellow SB2040.",
    ),
    "fysetc_spider_f446_usb": BoardPreset(
        id="fysetc_spider_f446_usb",
        vendor="Fysetc",
        name="Fysetc Spider STM32F446 USB",
        mcu="stm32f446",
        architecture="stm32",
        connection_type="usb",
        communication="USB",
        bootloader_offset="32KiB",
        canbus_pins=None,
        build_output="out/klipper.bin",
        default_flash_method="dfu_usb",
        notes="Preset inicial para Spider F446 via USB.",
    ),
    "fysetc_sb_can_g0b1": BoardPreset(
        id="fysetc_sb_can_g0b1",
        vendor="Fysetc",
        name="Fysetc SB CAN STM32G0B1",
        mcu="stm32g0b1",
        architecture="stm32",
        connection_type="can",
        communication="CAN bus",
        bootloader_offset="8KiB",
        canbus_pins="PB0/PB1",
        build_output="out/klipper.bin",
        default_flash_method="katapult_can",
        notes="Preset inicial para toolhead CAN Fysetc.",
    ),
}
