from __future__ import annotations


from app.modules.community.catalog_contracts import (
    TrustState,
    CatalogVariant,
    CatalogVariantDetail,
    CatalogModelAdmin,
    CatalogModel,
    CatalogManufacturer,
    CatalogSummary,
    CatalogAdminSummary,
    CatalogVariantUpdate,
    CatalogManufacturerCreate,
    CatalogModelCreate,
    CatalogVariantCreate,
)

from app.modules.community.community_contracts import (
    ProfileVisibility,
    CommunityStatus,
    RelationshipType,
    RelationshipStatus,
    FeedContentType,
    FeedOrder,
    DiscussionReactionType,
    PublicProfileUpdate,
    PublicProfile,
    PrinterPublicUpdate,
    PublicPrinter,
    Community,
    CommunityDetail,
    CommunityFeedItem,
    CommunityFeedSummary,
    CommunityFeedCreate,
    CommunityPostCreate,
    CommunityPostUpdate,
    DiscussionComment,
    DiscussionCommentCreate,
    DiscussionCommentUpdate,
    DiscussionReactionCount,
    DiscussionReactionPayload,
    DiscussionDetail,
    RelationshipRecord,
    RelationshipSummary,
)

from app.modules.community.library_contracts import (
    LibraryVisibility,
    LibraryFileKind,
    LibraryLicense,
    LibraryCollectionVisibility,
    PrintListItemStatus,
    LibraryContentClass,
    LibraryCommercialStatus,
    LibraryFileMetadata,
    LibraryItemBase,
    LibraryItemCreate,
    LibraryItemUpdate,
    LibraryVersionCreate,
    LibraryVersion,
    LibraryCollectionCreate,
    LibraryCollectionItemCreate,
    LibraryCollection,
    PrintListCreate,
    PrintListItemCreate,
    PrintListItemUpdate,
    PrintListItem,
    PrintList,
    LibraryDownloadHistoryItem,
    LibraryOrganizerSummary,
    LibraryItem,
    LibraryCommercialReviewCreate,
)

from app.modules.community.validation import (
    normalize_slug,
    clean_optional_text,
    clean_library_file_name,
    clean_text_list,
    clean_public_image_urls,
    clean_discussion_text,
    clean_discussion_attachments,
    validate_public_url,
    _is_private_or_local_host,
    _clean_social_links,
)
