CREATE TABLE IF NOT EXISTS calibration_tests (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    test_key TEXT NOT NULL UNIQUE,
    category TEXT NOT NULL,
    title TEXT NOT NULL,
    objective TEXT NOT NULL,
    source TEXT NOT NULL,
    execution_mode TEXT NOT NULL,
    risk_level TEXT NOT NULL,
    blocked_while_printing INTEGER NOT NULL DEFAULT 1,
    prerequisites_json TEXT NOT NULL,
    gcode_json TEXT NOT NULL,
    success_criteria_json TEXT NOT NULL,
    notes TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_calibration_tests_category_sort
ON calibration_tests(category, sort_order);

INSERT OR IGNORE INTO calibration_tests (
    test_key, category, title, objective, source, execution_mode, risk_level,
    blocked_while_printing, prerequisites_json, gcode_json, success_criteria_json, notes, sort_order
) VALUES
(
    'homing_endstops',
    'validacao_mecanica',
    'Homing e endstops',
    'Confirmar que eixos, endstops e direção de movimento estão coerentes antes de calibrações maiores.',
    'Klipper/Voron',
    'gcode_review_required',
    'medium',
    1,
    '["Impressora livre de obstruções", "Toolhead sem peça na mesa", "Operador presente no primeiro teste"]',
    '["G28"]',
    '["Todos os eixos fazem homing sem colisão", "Posição final coerente com a cinemática", "Nenhum erro de endstop ou movimento"]',
    'Executar somente com observação física da máquina.',
    10
),
(
    'quad_gantry_level',
    'nivelamento',
    'Quad Gantry Level',
    'Alinhar o gantry da Voron 2.4 usando os quatro motores Z.',
    'Klipper/Voron',
    'gcode_review_required',
    'medium',
    1,
    '["Homing concluído", "Probe confiável", "Mesa limpa", "Toolhead acoplado corretamente"]',
    '["G28", "QUAD_GANTRY_LEVEL", "G28 Z"]',
    '["QGL termina sem erro", "Range final dentro da tolerância configurada", "Sem retries excessivos de probe"]',
    'Não usar em impressoras sem QGL configurado.',
    20
),
(
    'probe_accuracy_center',
    'probe',
    'Probe Accuracy no centro',
    'Medir repetibilidade do probe em posição central antes de mesh ou primeira camada.',
    'Klipper',
    'gcode_review_required',
    'low',
    1,
    '["Homing concluído", "Bico limpo", "Superfície limpa", "Temperatura estável se o probe depender de calor"]',
    '["G28", "G0 X175 Y175 Z10 F12000", "PROBE_ACCURACY SAMPLES=10"]',
    '["Range baixo e repetível", "Sem Probe samples exceed tolerance", "Desvio compatível com o tipo de probe"]',
    'Coordenadas centrais assumem volume 350x350; tornar parametrizável em etapa futura.',
    30
),
(
    'bed_mesh_regular',
    'nivelamento',
    'Bed Mesh regular',
    'Mapear a superfície da mesa depois de homing e QGL bem-sucedidos.',
    'Klipper',
    'gcode_review_required',
    'medium',
    1,
    '["Gantry nivelado", "Probe confiável", "Mesa limpa", "Config de mesh validada"]',
    '["G28", "QUAD_GANTRY_LEVEL", "G28 Z", "BED_MESH_CALIBRATE"]',
    '["Mesh conclui sem erro", "Range compatível com a mesa", "Perfil salvo somente após revisão visual"]',
    'SAVE_CONFIG reinicia o Klipper; executar conscientemente.',
    40
),
(
    'first_layer',
    'primeira_camada',
    'Primeira camada',
    'Validar aderência, Z-offset e fluxo inicial com um teste controlado.',
    'Voron/Comunidade',
    'manual',
    'medium',
    1,
    '["Mesa limpa", "Filamento seco", "Z-offset revisado", "Temperaturas adequadas ao material"]',
    '[]',
    '["Linhas aderem sem raspar", "Sem falha de adesão", "Sem excesso de esmagamento", "Cantos permanecem presos"]',
    'G-code depende do slicer/material; catálogo apenas orienta o teste nesta etapa.',
    50
),
(
    'extrusion_flow',
    'extrusao',
    'Extrusão e flow',
    'Validar fluxo real do material antes de ajustes finos de velocidade e qualidade.',
    'Klipper/Comunidade',
    'manual',
    'medium',
    1,
    '["Extrusor aquecido", "Filamento carregado", "Esteps/rotation_distance revisados", "Perfil do slicer conhecido"]',
    '[]',
    '["Paredes com espessura previsível", "Sem under/over extrusion evidente", "Sem salto no extrusor"]',
    'Não altera rotation_distance automaticamente.',
    60
),
(
    'pressure_advance',
    'extrusao',
    'Pressure Advance',
    'Ajustar avanço de pressão para reduzir cantos inchados e melhorar transições de fluxo.',
    'Klipper',
    'manual',
    'medium',
    1,
    '["Flow básico estável", "Temperatura e velocidade definidas", "Material conhecido"]',
    '[]',
    '["Cantos consistentes", "Menos bulging", "Sem falhas de extrusão em aceleração"]',
    'Teste depende de modelo/G-code específico; execução futura deve exibir o G-code antes.',
    70
),
(
    'input_shaper',
    'movimento',
    'Input Shaper',
    'Validar ou recalibrar compensação de ressonância dos eixos.',
    'Klipper',
    'manual',
    'medium',
    1,
    '["Acelerômetro instalado ou método manual definido", "Correias revisadas", "Parafusos apertados", "Toolhead sem folga"]',
    '[]',
    '["Frequências coerentes", "Redução de ringing", "Sem ruído mecânico anormal"]',
    'Coleta automática com acelerômetro fica para pacote posterior.',
    80
),
(
    'speed_acceleration',
    'movimento',
    'Velocidade e aceleração',
    'Avaliar limites práticos sem perder qualidade ou confiabilidade mecânica.',
    'Voron/Comunidade',
    'manual',
    'high',
    1,
    '["Input Shaper válido", "Extrusão estável", "Temperaturas controladas", "Peça de teste adequada"]',
    '[]',
    '["Sem layer shift", "Sem ringing excessivo", "Sem perda de passos", "Temperaturas seguras"]',
    'Aumentos agressivos devem ser incrementais e registrados.',
    90
),
(
    'ringing_ghosting',
    'qualidade',
    'Ringing e ghosting',
    'Inspecionar artefatos de vibração em paredes e cantos.',
    'Voron/Comunidade',
    'manual',
    'low',
    1,
    '["Input Shaper configurado", "Peça de teste impressa", "Iluminação adequada para inspeção"]',
    '[]',
    '["Ondulações reduzidas", "Cantos limpos", "Sem vibração mecânica evidente"]',
    'Resultado é visual e deve aceitar fotos/notas em etapa futura.',
    100
),
(
    'cooling_bridging',
    'qualidade',
    'Cooling e bridging',
    'Avaliar refrigeração de peça, bridges e overhangs.',
    'Voron/Comunidade',
    'manual',
    'low',
    1,
    '["Fan de peça funcional", "Material conhecido", "Perfil de slicer controlado"]',
    '[]',
    '["Bridges sem queda excessiva", "Overhangs limpos", "Sem perda de adesão entre camadas"]',
    'Útil após alterações em duct/fan/toolhead.',
    110
),
(
    'dimensional_accuracy',
    'qualidade',
    'Precisão dimensional',
    'Comparar dimensões reais de peça de teste contra o modelo.',
    'Voron/Comunidade',
    'manual',
    'low',
    1,
    '["Fluxo básico calibrado", "Temperatura estável", "Paquímetro disponível"]',
    '[]',
    '["Medidas dentro da tolerância definida", "Eixos X/Y coerentes", "Sem deformação térmica relevante"]',
    'Correções devem separar slicer, material, mecânica e escala.',
    120
),
(
    'jog_xy_control',
    'movimento',
    'Movimento XY controlado',
    'Validar deslocamento curto em X ou Y com observação presencial.',
    'Klipper',
    'gcode_review_required',
    'medium',
    1,
    '["Homing concluído", "Área livre", "Operador presente", "Distância revisada antes de executar"]',
    '["G91", "G0 X10 F6000", "G90"]',
    '["Toolhead move somente a distância esperada", "Nenhuma colisão", "Nenhum erro de movimento"]',
    'Trocar X por Y ou ajustar distância somente depois de revisar o G-code exibido.',
    130
),
(
    'jog_z_control',
    'movimento',
    'Movimento Z controlado',
    'Validar deslocamento curto em Z sem tocar a mesa.',
    'Klipper',
    'gcode_review_required',
    'high',
    1,
    '["Homing concluído", "Bico afastado da mesa", "Área livre", "Operador presente"]',
    '["G91", "G0 Z5 F1200", "G90"]',
    '["Eixo Z move somente a distância esperada", "Bico permanece longe da mesa", "Nenhum erro de movimento"]',
    'Usar distância pequena e revisar sentido do eixo antes da execução.',
    140
),
(
    'hotend_heat_control',
    'temperatura',
    'Aquecimento do hotend',
    'Validar resposta do heater do hotend com alvo baixo e supervisionado.',
    'Klipper',
    'gcode_review_required',
    'medium',
    1,
    '["Hotend limpo", "Ventilação ativa", "Operador presente", "Alvo de temperatura revisado"]',
    '["SET_HEATER_TEMPERATURE HEATER=extruder TARGET=150"]',
    '["Temperatura sobe de forma previsível", "Sem thermal runaway", "Potência retorna ao esperado"]',
    'Ajustar alvo conforme material somente depois de revisar o G-code.',
    150
),
(
    'bed_heat_control',
    'temperatura',
    'Aquecimento da mesa',
    'Validar resposta do heater da mesa com alvo baixo e supervisionado.',
    'Klipper',
    'gcode_review_required',
    'medium',
    1,
    '["Mesa livre", "Operador presente", "Alvo de temperatura revisado"]',
    '["SET_HEATER_TEMPERATURE HEATER=heater_bed TARGET=50"]',
    '["Temperatura sobe de forma previsível", "Sem erro de heater", "Potência retorna ao esperado"]',
    'Ajustar alvo conforme material somente depois de revisar o G-code.',
    160
),
(
    'part_fan_control',
    'perifericos',
    'Fan de peça',
    'Validar acionamento do fan de peça em potência limitada.',
    'Klipper',
    'gcode_review_required',
    'low',
    1,
    '["Fan livre de obstruções", "Operador presente", "Ruído anormal monitorado"]',
    '["M106 S128", "M107"]',
    '["Fan liga e desliga corretamente", "Sem vibração anormal", "RPM coerente quando disponível"]',
    'Usar potência limitada no primeiro teste.',
    170
),
(
    'led_control',
    'perifericos',
    'LEDs',
    'Validar LED configurado no Klipper sem misturar com operação diária.',
    'Klipper',
    'manual',
    'low',
    1,
    '["Nome real do objeto LED identificado", "Operador presente", "Efeito atual conhecido"]',
    '[]',
    '["LED responde ao comando esperado", "Nenhum efeito crítico é sobrescrito", "Estado anterior pode ser restaurado manualmente"]',
    'SET_LED depende do nome real do objeto; registrar comando usado no resultado do teste.',
    180
),
(
    'manual_extrusion_control',
    'extrusao',
    'Extrusão manual controlada',
    'Validar avanço curto do extrusor com hotend em temperatura segura.',
    'Klipper',
    'gcode_review_required',
    'medium',
    1,
    '["Hotend aquecido acima da temperatura mínima", "Filamento carregado", "Operador presente", "Caminho do filamento livre"]',
    '["M83", "G1 E5 F300", "M82"]',
    '["Extrusor avança sem salto", "Filamento sai de forma estável", "Nenhum entupimento aparente"]',
    'Não executar frio; validar temperatura antes da extrusão.',
    190
),
(
    'mechanical_preflight',
    'validacao_mecanica',
    'Inspeção mecânica guiada',
    'Confirmar correias, polias, mesa, toolhead, cabos e folgas antes de qualquer ajuste fino.',
    'MayderPrintLab',
    'manual',
    'low',
    1,
    '["Impressora parada", "Ferramentas básicas disponíveis", "Usuário consegue mover e inspecionar a máquina com segurança"]',
    '[]',
    '["Correias sem folga excessiva", "Toolhead firme", "Mesa limpa e estável", "Cabos sem prender no movimento"]',
    'Base para leigos: se a mecânica estiver ruim, calibração por software mascara problema físico.',
    5
),
(
    'pid_hotend',
    'temperatura',
    'PID do hotend',
    'Estabilizar o controle de temperatura do hotend antes de calibrar material e fluxo.',
    'Klipper',
    'gcode_review_required',
    'medium',
    1,
    '["Hotend limpo", "Ventilação funcionando", "Operador presente", "Temperatura alvo adequada ao material"]',
    '["PID_CALIBRATE HEATER=extruder TARGET=220"]',
    '["Temperatura estabiliza sem oscilar muito", "Klipper conclui o PID sem erro", "Resultado é salvo conscientemente depois de revisão"]',
    'O alvo deve ser ajustado ao material usado. SAVE_CONFIG reinicia o Klipper.',
    12
),
(
    'pid_bed',
    'temperatura',
    'PID da mesa',
    'Estabilizar o aquecimento da mesa para primeira camada e peças grandes.',
    'Klipper',
    'gcode_review_required',
    'medium',
    1,
    '["Mesa livre", "Chapa correta instalada", "Operador presente", "Temperatura alvo revisada"]',
    '["PID_CALIBRATE HEATER=heater_bed TARGET=60"]',
    '["Mesa aquece de forma previsível", "Klipper conclui o PID sem erro", "Temperatura fica estável no alvo"]',
    'O alvo deve ser ajustado ao material. SAVE_CONFIG reinicia o Klipper.',
    14
),
(
    'extruder_rotation_distance',
    'extrusao_base',
    'Rotation distance do extrusor',
    'Conferir se o extrusor empurra a quantidade correta de filamento antes de flow e pressure advance.',
    'Klipper',
    'gcode_review_required',
    'medium',
    1,
    '["Hotend aquecido", "Filamento carregado", "Paquímetro disponível", "Marca no filamento feita pelo usuário"]',
    '["G91", "G1 E50 F60", "G90"]',
    '["Extrusão real próxima de 50 mm", "Sem salto no extrusor", "Novo valor calculado é revisado antes de alterar config"]',
    'Klipper recomenda extrusão lenta para medir; o app deve registrar medida e cálculo antes de qualquer mudança futura.',
    16
),
(
    'probe_xy_offset',
    'probe',
    'Offset XY do probe',
    'Alinhar a posição XY do probe em relação ao bico para melhorar mesh e Z-offset.',
    'Klipper',
    'manual',
    'medium',
    1,
    '["Probe instalado", "Mesa com fita ou referência visual", "Homing concluído", "Operador presente"]',
    '[]',
    '["Ponto do probe e ponto do bico são medidos", "Offset é conhecido", "Usuário entende que alterar config exige backup"]',
    'Procedimento é visual/manual; comandos e mudança de config ficam fora do app até haver fluxo dedicado.',
    22
),
(
    'gantry_or_bed_tram',
    'nivelamento',
    'Tram da mesa ou gantry',
    'Nivelar a geometria da máquina conforme o tipo: QGL, Z_TILT, screws_tilt ou ajuste manual.',
    'Klipper',
    'manual',
    'medium',
    1,
    '["Tipo de impressora identificado", "Homing concluído", "Probe confiável ou método manual definido"]',
    '[]',
    '["Plano mecânico corrigido antes do mesh", "Sem colisão", "Método usado fica registrado"]',
    'Genérico para todas as impressoras: Voron usa QGL; bedslinger pode usar screws_tilt_adjust ou nivelamento manual.',
    24
),
(
    'temperature_tower',
    'material',
    'Torre de temperatura',
    'Escolher a melhor temperatura do filamento antes de flow, retração e velocidade.',
    'OrcaSlicer',
    'manual',
    'low',
    1,
    '["Filamento identificado", "Perfil do slicer selecionado", "Peça de torre gerada no slicer"]',
    '[]',
    '["Camada com melhor brilho, adesão e ponte escolhida", "Temperatura registrada por material", "Sem sinais de queima ou underextrusion"]',
    'Calibração dependente de material, marca, cor e nozzle.',
    52
),
(
    'max_volumetric_speed',
    'material',
    'Velocidade volumétrica máxima',
    'Encontrar o limite real de fluxo do hotend para evitar underextrusion em alta velocidade.',
    'OrcaSlicer',
    'manual',
    'medium',
    1,
    '["Temperatura definida", "Flow base razoável", "Filamento seco", "Teste gerado no slicer"]',
    '[]',
    '["Limite de mm3/s identificado", "Sem falha de extrusão no valor escolhido", "Perfil do material atualizado conscientemente"]',
    'Deve ser por material/nozzle/hotend. Não é igual para todos os filamentos.',
    54
),
(
    'flow_rate_pass_1',
    'material',
    'Flow rate - passe 1',
    'Ajustar o multiplicador de fluxo do material com teste visual de superfície.',
    'OrcaSlicer',
    'manual',
    'low',
    1,
    '["Temperatura escolhida", "Velocidade volumétrica segura", "Perfil do slicer separado para o material"]',
    '[]',
    '["Superfície superior lisa", "Sem excesso nas bordas", "Valor de flow inicial registrado"]',
    'Primeiro passe aproxima o valor; o segundo passe refina.',
    56
),
(
    'flow_rate_pass_2',
    'material',
    'Flow rate - passe 2',
    'Refinar o fluxo depois do primeiro ajuste para acabamento impecável.',
    'OrcaSlicer',
    'manual',
    'low',
    1,
    '["Flow pass 1 concluído", "Mesma chapa/material/nozzle", "Peça avaliada com boa iluminação"]',
    '[]',
    '["Linha superior uniforme", "Sem lacunas", "Sem excesso visível", "Valor final registrado"]',
    'Refino fino por material e cor.',
    58
),
(
    'retraction_tuning',
    'material',
    'Retração',
    'Reduzir stringing e oozing depois de temperatura, flow e pressure advance.',
    'OrcaSlicer',
    'manual',
    'low',
    1,
    '["Temperatura definida", "Flow e pressure advance revisados", "Filamento seco"]',
    '[]',
    '["Poucos fios entre torres", "Sem falhas após retração", "Superfície sem blobs relevantes"]',
    'Ajuste depende do extrusor, material e hotend.',
    72
),
(
    'dimensional_skew',
    'dimensional',
    'Skew e precisão dimensional',
    'Corrigir esquadro e medidas finais quando a mecânica está boa, mas peças ainda saem fora de medida.',
    'Klipper/OrcaSlicer',
    'manual',
    'medium',
    1,
    '["Paquímetro disponível", "Peça de calibração impressa", "Flow calibrado", "Mecânica sem folga"]',
    '[]',
    '["Medidas XYZ registradas", "Skew calculado se necessário", "Correção não empurra movimentos para fora da área útil"]',
    'Klipper recomenda corrigir mecanicamente primeiro quando o desalinhamento for grande.',
    122
);
