CREATE TABLE IF NOT EXISTS calibration_tests (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    test_key TEXT NOT NULL UNIQUE,
    category TEXT NOT NULL,
    title TEXT NOT NULL,
    objective TEXT NOT NULL,
    source TEXT NOT NULL,
    execution_mode TEXT NOT NULL,
    risk_level TEXT NOT NULL,
    blocked_while_printing INTEGER NOT NULL DEFAULT 1,
    prerequisites_json TEXT NOT NULL,
    gcode_json TEXT NOT NULL,
    success_criteria_json TEXT NOT NULL,
    notes TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_calibration_tests_category_sort
ON calibration_tests(category, sort_order);

INSERT OR IGNORE INTO calibration_tests (
    test_key, category, title, objective, source, execution_mode, risk_level,
    blocked_while_printing, prerequisites_json, gcode_json, success_criteria_json, notes, sort_order
) VALUES
(
    'homing_endstops',
    'validacao_mecanica',
    'Homing e endstops',
    'Confirmar que eixos, endstops e direção de movimento estão coerentes antes de calibrações maiores.',
    'Klipper/Voron',
    'gcode_review_required',
    'medium',
    1,
    '["Impressora livre de obstruções", "Toolhead sem peça na mesa", "Operador presente no primeiro teste"]',
    '["G28"]',
    '["Todos os eixos fazem homing sem colisão", "Posição final coerente com a cinemática", "Nenhum erro de endstop ou movimento"]',
    'Executar somente com observação física da máquina.',
    10
),
(
    'quad_gantry_level',
    'nivelamento',
    'Quad Gantry Level',
    'Alinhar o gantry da Voron 2.4 usando os quatro motores Z.',
    'Klipper/Voron',
    'gcode_review_required',
    'medium',
    1,
    '["Homing concluído", "Probe confiável", "Mesa limpa", "Toolhead acoplado corretamente"]',
    '["G28", "QUAD_GANTRY_LEVEL", "G28 Z"]',
    '["QGL termina sem erro", "Range final dentro da tolerância configurada", "Sem retries excessivos de probe"]',
    'Não usar em impressoras sem QGL configurado.',
    20
),
(
    'probe_accuracy_center',
    'probe',
    'Probe Accuracy no centro',
    'Medir repetibilidade do probe em posição central antes de mesh ou primeira camada.',
    'Klipper',
    'gcode_review_required',
    'low',
    1,
    '["Homing concluído", "Bico limpo", "Superfície limpa", "Temperatura estável se o probe depender de calor"]',
    '["G28", "G0 X175 Y175 Z10 F12000", "PROBE_ACCURACY SAMPLES=10"]',
    '["Range baixo e repetível", "Sem Probe samples exceed tolerance", "Desvio compatível com o tipo de probe"]',
    'Coordenadas centrais assumem volume 350x350; tornar parametrizável em etapa futura.',
    30
),
(
    'bed_mesh_regular',
    'nivelamento',
    'Bed Mesh regular',
    'Mapear a superfície da mesa depois de homing e QGL bem-sucedidos.',
    'Klipper',
    'gcode_review_required',
    'medium',
    1,
    '["Gantry nivelado", "Probe confiável", "Mesa limpa", "Config de mesh validada"]',
    '["G28", "QUAD_GANTRY_LEVEL", "G28 Z", "BED_MESH_CALIBRATE"]',
    '["Mesh conclui sem erro", "Range compatível com a mesa", "Perfil salvo somente após revisão visual"]',
    'SAVE_CONFIG reinicia o Klipper; executar conscientemente.',
    40
),
(
    'first_layer',
    'primeira_camada',
    'Primeira camada',
    'Validar aderência, Z-offset e fluxo inicial com um teste controlado.',
    'Voron/Comunidade',
    'manual',
    'medium',
    1,
    '["Mesa limpa", "Filamento seco", "Z-offset revisado", "Temperaturas adequadas ao material"]',
    '[]',
    '["Linhas aderem sem raspar", "Sem falha de adesão", "Sem excesso de esmagamento", "Cantos permanecem presos"]',
    'G-code depende do slicer/material; catálogo apenas orienta o teste nesta etapa.',
    50
),
(
    'extrusion_flow',
    'extrusao',
    'Extrusão e flow',
    'Validar fluxo real do material antes de ajustes finos de velocidade e qualidade.',
    'Klipper/Comunidade',
    'manual',
    'medium',
    1,
    '["Extrusor aquecido", "Filamento carregado", "Esteps/rotation_distance revisados", "Perfil do slicer conhecido"]',
    '[]',
    '["Paredes com espessura previsível", "Sem under/over extrusion evidente", "Sem salto no extrusor"]',
    'Não altera rotation_distance automaticamente.',
    60
),
(
    'pressure_advance',
    'extrusao',
    'Pressure Advance',
    'Ajustar avanço de pressão para reduzir cantos inchados e melhorar transições de fluxo.',
    'Klipper',
    'manual',
    'medium',
    1,
    '["Flow básico estável", "Temperatura e velocidade definidas", "Material conhecido"]',
    '[]',
    '["Cantos consistentes", "Menos bulging", "Sem falhas de extrusão em aceleração"]',
    'Teste depende de modelo/G-code específico; execução futura deve exibir o G-code antes.',
    70
),
(
    'input_shaper',
    'movimento',
    'Input Shaper',
    'Validar ou recalibrar compensação de ressonância dos eixos.',
    'Klipper',
    'manual',
    'medium',
    1,
    '["Acelerômetro instalado ou método manual definido", "Correias revisadas", "Parafusos apertados", "Toolhead sem folga"]',
    '[]',
    '["Frequências coerentes", "Redução de ringing", "Sem ruído mecânico anormal"]',
    'Coleta automática com acelerômetro fica para pacote posterior.',
    80
),
(
    'speed_acceleration',
    'movimento',
    'Velocidade e aceleração',
    'Avaliar limites práticos sem perder qualidade ou confiabilidade mecânica.',
    'Voron/Comunidade',
    'manual',
    'high',
    1,
    '["Input Shaper válido", "Extrusão estável", "Temperaturas controladas", "Peça de teste adequada"]',
    '[]',
    '["Sem layer shift", "Sem ringing excessivo", "Sem perda de passos", "Temperaturas seguras"]',
    'Aumentos agressivos devem ser incrementais e registrados.',
    90
),
(
    'ringing_ghosting',
    'qualidade',
    'Ringing e ghosting',
    'Inspecionar artefatos de vibração em paredes e cantos.',
    'Voron/Comunidade',
    'manual',
    'low',
    1,
    '["Input Shaper configurado", "Peça de teste impressa", "Iluminação adequada para inspeção"]',
    '[]',
    '["Ondulações reduzidas", "Cantos limpos", "Sem vibração mecânica evidente"]',
    'Resultado é visual e deve aceitar fotos/notas em etapa futura.',
    100
),
(
    'cooling_bridging',
    'qualidade',
    'Cooling e bridging',
    'Avaliar refrigeração de peça, bridges e overhangs.',
    'Voron/Comunidade',
    'manual',
    'low',
    1,
    '["Fan de peça funcional", "Material conhecido", "Perfil de slicer controlado"]',
    '[]',
    '["Bridges sem queda excessiva", "Overhangs limpos", "Sem perda de adesão entre camadas"]',
    'Útil após alterações em duct/fan/toolhead.',
    110
),
(
    'dimensional_accuracy',
    'qualidade',
    'Precisão dimensional',
    'Comparar dimensões reais de peça de teste contra o modelo.',
    'Voron/Comunidade',
    'manual',
    'low',
    1,
    '["Fluxo básico calibrado", "Temperatura estável", "Paquímetro disponível"]',
    '[]',
    '["Medidas dentro da tolerância definida", "Eixos X/Y coerentes", "Sem deformação térmica relevante"]',
    'Correções devem separar slicer, material, mecânica e escala.',
    120
);
