import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import ts from "typescript";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

const source = await readFile(join(root, "src/components/monitoring/gcodePreview.ts"), "utf8");
const transpiled = ts.transpileModule(source, {
  compilerOptions: {
    target: ts.ScriptTarget.ES2022,
    module: ts.ModuleKind.ES2022,
  },
});
const moduleUrl = `data:text/javascript;base64,${Buffer.from(transpiled.outputText).toString("base64")}`;
const { buildLayerOffsets, previewTargetPosition, sliceGcodeTextForPreview } = await import(moduleUrl);

const moves = Array.from({ length: 12 }, (_, index) => `G1 X${index} Y${index} E${(index + 1) / 10}`).join("\n");
const gcode = [
  "; generated by test fixture",
  moves,
  ";AFTER_LAYER_CHANGE",
  moves,
  ";AFTER_LAYER_CHANGE",
  moves,
  ";AFTER_LAYER_CHANGE",
  moves,
].join("\n");
const fileSize = gcode.length;
const offsets = buildLayerOffsets(gcode);

assert.ok(offsets.length >= 4);
assert.equal(previewTargetPosition(fileSize, offsets, "full"), fileSize);
assert.equal(previewTargetPosition(fileSize, offsets, "until_layer", 1, null, "printing", null, null, 3), offsets[2]);
assert.equal(previewTargetPosition(fileSize, offsets, "current_layer", 2, null, "printing", null, null, 3), offsets[3]);
assert.equal(previewTargetPosition(fileSize, offsets, "progress", null, null, "complete", 0.25, 1, 3), fileSize);
assert.equal(previewTargetPosition(1000, [], "progress", null, 800, "printing", null, null, null), 450);
assert.equal(previewTargetPosition(1000, [], "progress", null, null, "printing", 25, null, null), 250);
assert.equal(previewTargetPosition(1000, [0, 400, 800, 1000], "progress", null, 900, "printing", null, 2, 3), 550);

const largeGcode = "G1 X1 Y1 E0.1\n".repeat(720000);
const partialSlice = sliceGcodeTextForPreview(largeGcode, 1024);
assert.equal(partialSlice.partial, true);
assert.ok(partialSlice.sourceLimit >= 8 * 1024 * 1024);
assert.ok(partialSlice.sourceLimit < largeGcode.length);
assert.equal(partialSlice.text, largeGcode.slice(0, partialSlice.sourceLimit));
assert.equal(partialSlice.text.endsWith("\n"), true);

const finalSlice = sliceGcodeTextForPreview(largeGcode, largeGcode.length - 512);
assert.equal(finalSlice.partial, false);
assert.equal(finalSlice.sourceLimit, largeGcode.length);

console.log("G-code preview tests passed.");
