CREATE TABLE IF NOT EXISTS finance_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    account_type TEXT NOT NULL CHECK(account_type IN ('asset', 'liability', 'equity', 'revenue', 'expense')),
    currency TEXT NOT NULL CHECK(length(currency) = 3 AND currency = upper(currency)),
    owner_user_id BIGINT REFERENCES auth_users(id) ON DELETE RESTRICT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS finance_ledger_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_key TEXT NOT NULL UNIQUE,
    command_digest TEXT NOT NULL,
    operation_type TEXT NOT NULL,
    currency TEXT NOT NULL CHECK(length(currency) = 3 AND currency = upper(currency)),
    status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft', 'posted')),
    correlation_id TEXT NOT NULL,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_by_user_id BIGINT REFERENCES auth_users(id) ON DELETE RESTRICT,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    posted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS finance_ledger_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT NOT NULL REFERENCES finance_ledger_transactions(id) ON DELETE RESTRICT,
    account_id BIGINT NOT NULL REFERENCES finance_accounts(id) ON DELETE RESTRICT,
    side TEXT NOT NULL CHECK(side IN ('debit', 'credit')),
    amount_minor BIGINT NOT NULL CHECK(amount_minor > 0),
    currency TEXT NOT NULL CHECK(length(currency) = 3 AND currency = upper(currency)),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_finance_ledger_entries_transaction
ON finance_ledger_entries(transaction_id, side);
CREATE INDEX IF NOT EXISTS idx_finance_ledger_entries_account
ON finance_ledger_entries(account_id, created_at);

CREATE OR REPLACE FUNCTION printora_finance_ledger_guard() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    transaction_currency TEXT;
    transaction_status TEXT;
    account_currency TEXT;
    account_active BOOLEAN;
BEGIN
    SELECT currency, status INTO transaction_currency, transaction_status
    FROM finance_ledger_transactions WHERE id = NEW.transaction_id FOR UPDATE;
    SELECT currency, is_active INTO account_currency, account_active
    FROM finance_accounts WHERE id = NEW.account_id;
    IF transaction_status <> 'draft' OR transaction_currency <> NEW.currency
       OR account_currency <> NEW.currency OR account_active IS NOT TRUE THEN
        RAISE EXCEPTION 'finance ledger currency/account guard';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION printora_finance_posting_guard() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    entry_count BIGINT;
    balance BIGINT;
BEGIN
    IF OLD.status = 'posted' THEN
        RAISE EXCEPTION 'posted finance ledger transaction is immutable';
    END IF;
    IF NEW.status = 'posted' THEN
        SELECT COUNT(*), COALESCE(SUM(CASE WHEN side = 'debit' THEN amount_minor ELSE -amount_minor END), 0)
        INTO entry_count, balance
        FROM finance_ledger_entries WHERE transaction_id = OLD.id;
        IF entry_count < 2 OR balance <> 0 THEN
            RAISE EXCEPTION 'finance ledger transaction is not balanced';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION printora_finance_immutable() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'finance ledger row is immutable';
END;
$$;

DROP TRIGGER IF EXISTS finance_ledger_entry_currency_guard ON finance_ledger_entries;
CREATE TRIGGER finance_ledger_entry_currency_guard
BEFORE INSERT ON finance_ledger_entries
FOR EACH ROW EXECUTE FUNCTION printora_finance_ledger_guard();

DROP TRIGGER IF EXISTS finance_ledger_posting_balance_guard ON finance_ledger_transactions;
CREATE TRIGGER finance_ledger_posting_balance_guard
BEFORE UPDATE ON finance_ledger_transactions
FOR EACH ROW EXECUTE FUNCTION printora_finance_posting_guard();

DROP TRIGGER IF EXISTS finance_ledger_transactions_no_delete ON finance_ledger_transactions;
CREATE TRIGGER finance_ledger_transactions_no_delete
BEFORE DELETE ON finance_ledger_transactions
FOR EACH ROW EXECUTE FUNCTION printora_finance_immutable();

DROP TRIGGER IF EXISTS finance_ledger_entries_immutable_update ON finance_ledger_entries;
CREATE TRIGGER finance_ledger_entries_immutable_update
BEFORE UPDATE ON finance_ledger_entries
FOR EACH ROW EXECUTE FUNCTION printora_finance_immutable();

DROP TRIGGER IF EXISTS finance_ledger_entries_immutable_delete ON finance_ledger_entries;
CREATE TRIGGER finance_ledger_entries_immutable_delete
BEFORE DELETE ON finance_ledger_entries
FOR EACH ROW EXECUTE FUNCTION printora_finance_immutable();
