CREATE TABLE IF NOT EXISTS payment_intents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id TEXT NOT NULL UNIQUE,
    order_id BIGINT,
    provider TEXT NOT NULL,
    provider_intent_id TEXT NOT NULL UNIQUE,
    idempotency_key TEXT NOT NULL UNIQUE,
    command_digest TEXT NOT NULL,
    amount_minor BIGINT NOT NULL CHECK(amount_minor > 0),
    currency TEXT NOT NULL CHECK(length(currency) = 3 AND currency = upper(currency)),
    status TEXT NOT NULL CHECK(status IN (
        'requires_action', 'authorized', 'captured', 'cancelled', 'partially_refunded',
        'refunded', 'disputed', 'failed'
    )),
    hosted_checkout_url TEXT NOT NULL,
    latest_provider_event_at TIMESTAMPTZ,
    created_by_user_id BIGINT REFERENCES auth_users(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS payment_webhook_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider TEXT NOT NULL,
    provider_event_id TEXT NOT NULL,
    provider_intent_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    event_created_at TIMESTAMPTZ NOT NULL,
    payload_sha256 TEXT NOT NULL,
    signature_verified BOOLEAN NOT NULL,
    processing_status TEXT NOT NULL CHECK(processing_status IN ('processed', 'ignored_out_of_order', 'rejected')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(provider, provider_event_id)
);

CREATE INDEX IF NOT EXISTS idx_payment_intents_status
ON payment_intents(status, updated_at);
CREATE INDEX IF NOT EXISTS idx_payment_webhook_events_intent
ON payment_webhook_events(provider_intent_id, event_created_at);

DROP TRIGGER IF EXISTS payment_webhook_events_immutable_update ON payment_webhook_events;
CREATE TRIGGER payment_webhook_events_immutable_update
BEFORE UPDATE ON payment_webhook_events
FOR EACH ROW EXECUTE FUNCTION printora_finance_immutable();
DROP TRIGGER IF EXISTS payment_webhook_events_immutable_delete ON payment_webhook_events;
CREATE TRIGGER payment_webhook_events_immutable_delete
BEFORE DELETE ON payment_webhook_events
FOR EACH ROW EXECUTE FUNCTION printora_finance_immutable();
