CREATE TABLE IF NOT EXISTS commerce_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id TEXT NOT NULL UNIQUE,
    buyer_user_id BIGINT NOT NULL REFERENCES auth_users(id) ON DELETE RESTRICT,
    idempotency_key TEXT NOT NULL UNIQUE,
    command_digest TEXT NOT NULL,
    currency TEXT NOT NULL CHECK(length(currency) = 3 AND currency = upper(currency)),
    subtotal_minor BIGINT NOT NULL CHECK(subtotal_minor >= 0),
    fee_minor BIGINT NOT NULL DEFAULT 0 CHECK(fee_minor >= 0),
    tax_minor BIGINT NOT NULL DEFAULT 0 CHECK(tax_minor >= 0),
    total_minor BIGINT NOT NULL CHECK(total_minor >= 0),
    status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN (
        'draft', 'pending_payment', 'paid', 'cancelled', 'partially_refunded',
        'refunded', 'disputed'
    )),
    country_code TEXT NOT NULL DEFAULT 'BR',
    tax_status TEXT NOT NULL DEFAULT 'not_configured' CHECK(tax_status IN ('not_configured', 'prepared', 'reviewed')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS commerce_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES commerce_orders(id) ON DELETE RESTRICT,
    source_project_id BIGINT NOT NULL REFERENCES print_projects(id) ON DELETE RESTRICT,
    source_project_version_id BIGINT REFERENCES print_project_versions(id) ON DELETE RESTRICT,
    seller_user_id BIGINT REFERENCES auth_users(id) ON DELETE RESTRICT,
    title_snapshot TEXT NOT NULL,
    license_snapshot TEXT NOT NULL,
    terms_snapshot TEXT NOT NULL,
    project_snapshot_json TEXT NOT NULL,
    unit_price_minor BIGINT NOT NULL CHECK(unit_price_minor > 0),
    quantity BIGINT NOT NULL CHECK(quantity > 0 AND quantity <= 100),
    currency TEXT NOT NULL CHECK(length(currency) = 3 AND currency = upper(currency)),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_commerce_orders_buyer
ON commerce_orders(buyer_user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_commerce_orders_status
ON commerce_orders(status, updated_at);
CREATE INDEX IF NOT EXISTS idx_commerce_order_items_order
ON commerce_order_items(order_id, id);

CREATE OR REPLACE FUNCTION printora_commerce_order_guard() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.currency <> OLD.currency OR NEW.subtotal_minor <> OLD.subtotal_minor
       OR NEW.fee_minor <> OLD.fee_minor OR NEW.tax_minor <> OLD.tax_minor
       OR NEW.total_minor <> OLD.total_minor OR NEW.country_code <> OLD.country_code
       OR NEW.tax_status <> OLD.tax_status THEN
        RAISE EXCEPTION 'commerce order monetary snapshot is immutable';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS commerce_order_amounts_immutable ON commerce_orders;
CREATE TRIGGER commerce_order_amounts_immutable
BEFORE UPDATE ON commerce_orders
FOR EACH ROW EXECUTE FUNCTION printora_commerce_order_guard();
DROP TRIGGER IF EXISTS commerce_orders_no_delete ON commerce_orders;
CREATE TRIGGER commerce_orders_no_delete
BEFORE DELETE ON commerce_orders
FOR EACH ROW EXECUTE FUNCTION printora_finance_immutable();
DROP TRIGGER IF EXISTS commerce_order_items_immutable_update ON commerce_order_items;
CREATE TRIGGER commerce_order_items_immutable_update
BEFORE UPDATE ON commerce_order_items
FOR EACH ROW EXECUTE FUNCTION printora_finance_immutable();
DROP TRIGGER IF EXISTS commerce_order_items_immutable_delete ON commerce_order_items;
CREATE TRIGGER commerce_order_items_immutable_delete
BEFORE DELETE ON commerce_order_items
FOR EACH ROW EXECUTE FUNCTION printora_finance_immutable();

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_payment_intents_order'
    ) THEN
        ALTER TABLE payment_intents
        ADD CONSTRAINT fk_payment_intents_order
        FOREIGN KEY (order_id) REFERENCES commerce_orders(id) ON DELETE RESTRICT;
    END IF;
END;
$$;
