CREATE TABLE IF NOT EXISTS finance_payment_commands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_intent_id BIGINT NOT NULL REFERENCES payment_intents(id) ON DELETE RESTRICT,
    command_type TEXT NOT NULL CHECK(command_type IN ('capture', 'cancel', 'refund', 'open_dispute', 'resolve_dispute_won', 'resolve_dispute_lost')),
    idempotency_key TEXT NOT NULL UNIQUE,
    command_digest TEXT NOT NULL,
    amount_minor BIGINT,
    result_status TEXT NOT NULL,
    created_by_user_id BIGINT REFERENCES auth_users(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS payment_refunds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id TEXT NOT NULL UNIQUE,
    payment_intent_id BIGINT NOT NULL REFERENCES payment_intents(id) ON DELETE RESTRICT,
    order_id BIGINT REFERENCES commerce_orders(id) ON DELETE RESTRICT,
    amount_minor BIGINT NOT NULL CHECK(amount_minor > 0), currency TEXT NOT NULL,
    reason TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('succeeded')),
    command_id BIGINT NOT NULL UNIQUE REFERENCES finance_payment_commands(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS payment_refund_allocations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_id BIGINT NOT NULL REFERENCES payment_refunds(id) ON DELETE RESTRICT,
    seller_user_id BIGINT REFERENCES auth_users(id) ON DELETE RESTRICT,
    amount_minor BIGINT NOT NULL CHECK(amount_minor > 0), currency TEXT NOT NULL,
    UNIQUE(refund_id, seller_user_id)
);
CREATE TABLE IF NOT EXISTS payment_disputes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id TEXT NOT NULL UNIQUE,
    payment_intent_id BIGINT NOT NULL REFERENCES payment_intents(id) ON DELETE RESTRICT,
    order_id BIGINT REFERENCES commerce_orders(id) ON DELETE RESTRICT,
    amount_minor BIGINT NOT NULL CHECK(amount_minor > 0), currency TEXT NOT NULL,
    reason_code TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('open', 'won', 'lost')),
    opened_command_id BIGINT NOT NULL UNIQUE REFERENCES finance_payment_commands(id) ON DELETE RESTRICT,
    resolved_command_id BIGINT UNIQUE REFERENCES finance_payment_commands(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, resolved_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_finance_payment_commands_intent ON finance_payment_commands(payment_intent_id, created_at);
CREATE INDEX IF NOT EXISTS idx_payment_refunds_intent ON payment_refunds(payment_intent_id, created_at);
CREATE INDEX IF NOT EXISTS idx_payment_disputes_intent ON payment_disputes(payment_intent_id, status);

DROP TRIGGER IF EXISTS finance_payment_commands_immutable_update ON finance_payment_commands;
CREATE TRIGGER finance_payment_commands_immutable_update BEFORE UPDATE ON finance_payment_commands FOR EACH ROW EXECUTE FUNCTION printora_finance_immutable();
DROP TRIGGER IF EXISTS finance_payment_commands_immutable_delete ON finance_payment_commands;
CREATE TRIGGER finance_payment_commands_immutable_delete BEFORE DELETE ON finance_payment_commands FOR EACH ROW EXECUTE FUNCTION printora_finance_immutable();
DROP TRIGGER IF EXISTS payment_refunds_immutable_update ON payment_refunds;
CREATE TRIGGER payment_refunds_immutable_update BEFORE UPDATE ON payment_refunds FOR EACH ROW EXECUTE FUNCTION printora_finance_immutable();
DROP TRIGGER IF EXISTS payment_refunds_immutable_delete ON payment_refunds;
CREATE TRIGGER payment_refunds_immutable_delete BEFORE DELETE ON payment_refunds FOR EACH ROW EXECUTE FUNCTION printora_finance_immutable();
DROP TRIGGER IF EXISTS payment_refund_allocations_immutable_update ON payment_refund_allocations;
CREATE TRIGGER payment_refund_allocations_immutable_update BEFORE UPDATE ON payment_refund_allocations FOR EACH ROW EXECUTE FUNCTION printora_finance_immutable();
DROP TRIGGER IF EXISTS payment_refund_allocations_immutable_delete ON payment_refund_allocations;
CREATE TRIGGER payment_refund_allocations_immutable_delete BEFORE DELETE ON payment_refund_allocations FOR EACH ROW EXECUTE FUNCTION printora_finance_immutable();
DROP TRIGGER IF EXISTS payment_disputes_no_delete ON payment_disputes;
CREATE TRIGGER payment_disputes_no_delete BEFORE DELETE ON payment_disputes FOR EACH ROW EXECUTE FUNCTION printora_finance_immutable();
