CREATE TABLE IF NOT EXISTS finance_reconciliation_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id TEXT NOT NULL UNIQUE, provider TEXT NOT NULL, currency TEXT NOT NULL,
    ledger_clearing_minor BIGINT NOT NULL, provider_reported_minor BIGINT NOT NULL,
    difference_minor BIGINT NOT NULL, status TEXT NOT NULL CHECK(status IN ('passed', 'blocked')),
    evidence_sha256 TEXT NOT NULL,
    executed_by_user_id BIGINT REFERENCES auth_users(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS finance_payouts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id TEXT NOT NULL UNIQUE,
    seller_user_id BIGINT NOT NULL REFERENCES auth_users(id) ON DELETE RESTRICT,
    currency TEXT NOT NULL, amount_minor BIGINT NOT NULL CHECK(amount_minor > 0),
    status TEXT NOT NULL CHECK(status IN ('requested', 'approved', 'blocked', 'paid', 'cancelled')),
    idempotency_key TEXT NOT NULL UNIQUE, command_digest TEXT NOT NULL,
    requested_by_user_id BIGINT NOT NULL REFERENCES auth_users(id) ON DELETE RESTRICT,
    approved_by_user_id BIGINT REFERENCES auth_users(id) ON DELETE RESTRICT,
    paid_ledger_transaction_id BIGINT UNIQUE REFERENCES finance_ledger_transactions(id) ON DELETE RESTRICT,
    reconciliation_run_id BIGINT REFERENCES finance_reconciliation_runs(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, approved_at TIMESTAMPTZ, paid_at TIMESTAMPTZ,
    CHECK(approved_by_user_id IS NULL OR approved_by_user_id <> requested_by_user_id)
);
CREATE TABLE IF NOT EXISTS finance_closings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id TEXT NOT NULL UNIQUE, currency TEXT NOT NULL, period_key TEXT NOT NULL,
    reconciliation_run_id BIGINT NOT NULL REFERENCES finance_reconciliation_runs(id) ON DELETE RESTRICT,
    ledger_transaction_count BIGINT NOT NULL, ledger_imbalance_count BIGINT NOT NULL,
    open_dispute_count BIGINT NOT NULL, status TEXT NOT NULL CHECK(status IN ('closed', 'blocked')),
    closed_by_user_id BIGINT REFERENCES auth_users(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(currency, period_key)
);
CREATE INDEX IF NOT EXISTS idx_finance_payouts_seller ON finance_payouts(seller_user_id, status, created_at);
CREATE INDEX IF NOT EXISTS idx_finance_reconciliation_status ON finance_reconciliation_runs(currency, status, created_at);
DROP TRIGGER IF EXISTS finance_reconciliation_immutable_update ON finance_reconciliation_runs;
CREATE TRIGGER finance_reconciliation_immutable_update BEFORE UPDATE ON finance_reconciliation_runs FOR EACH ROW EXECUTE FUNCTION printora_finance_immutable();
DROP TRIGGER IF EXISTS finance_reconciliation_immutable_delete ON finance_reconciliation_runs;
CREATE TRIGGER finance_reconciliation_immutable_delete BEFORE DELETE ON finance_reconciliation_runs FOR EACH ROW EXECUTE FUNCTION printora_finance_immutable();
DROP TRIGGER IF EXISTS finance_payouts_no_delete ON finance_payouts;
CREATE TRIGGER finance_payouts_no_delete BEFORE DELETE ON finance_payouts FOR EACH ROW EXECUTE FUNCTION printora_finance_immutable();
DROP TRIGGER IF EXISTS finance_closings_immutable_update ON finance_closings;
CREATE TRIGGER finance_closings_immutable_update BEFORE UPDATE ON finance_closings FOR EACH ROW EXECUTE FUNCTION printora_finance_immutable();
DROP TRIGGER IF EXISTS finance_closings_immutable_delete ON finance_closings;
CREATE TRIGGER finance_closings_immutable_delete BEFORE DELETE ON finance_closings FOR EACH ROW EXECUTE FUNCTION printora_finance_immutable();
