CREATE TABLE IF NOT EXISTS finance_compliance_controls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    control_key TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL CHECK(status IN ('pending', 'passed', 'blocked')),
    evidence_sha256 TEXT,
    reviewed_by_user_id BIGINT REFERENCES auth_users(id) ON DELETE RESTRICT,
    reviewed_at TIMESTAMPTZ, expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS finance_retention_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_class TEXT NOT NULL UNIQUE,
    retention_days BIGINT NOT NULL CHECK(retention_days > 0),
    legal_basis TEXT NOT NULL,
    deletion_mode TEXT NOT NULL CHECK(deletion_mode IN ('restricted_financial_record', 'anonymize_after_retention')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO finance_compliance_controls (control_key, status) VALUES
    ('pci_scope', 'pending'), ('lgpd', 'pending'), ('fiscal_br', 'pending'),
    ('legal_br', 'pending'), ('provider_continuity', 'pending'),
    ('chargeback_runbook', 'pending'), ('security_review', 'pending'), ('restore_test', 'pending')
ON CONFLICT (control_key) DO NOTHING;
INSERT INTO finance_retention_policies (data_class, retention_days, legal_basis, deletion_mode) VALUES
    ('ledger_and_orders', 3650, 'obrigação legal e exercício regular de direitos', 'restricted_financial_record'),
    ('payment_webhook_digests', 730, 'prevenção a fraude e defesa em disputa', 'restricted_financial_record'),
    ('finance_audit', 180, 'segurança e prestação de contas', 'anonymize_after_retention'),
    ('risk_evidence', 730, 'prevenção a fraude e recurso', 'anonymize_after_retention')
ON CONFLICT (data_class) DO NOTHING;
DROP TRIGGER IF EXISTS finance_retention_policies_immutable_update ON finance_retention_policies;
CREATE TRIGGER finance_retention_policies_immutable_update BEFORE UPDATE ON finance_retention_policies FOR EACH ROW EXECUTE FUNCTION printora_finance_immutable();
DROP TRIGGER IF EXISTS finance_retention_policies_immutable_delete ON finance_retention_policies;
CREATE TRIGGER finance_retention_policies_immutable_delete BEFORE DELETE ON finance_retention_policies FOR EACH ROW EXECUTE FUNCTION printora_finance_immutable();
