CREATE TABLE IF NOT EXISTS manufacturing_quotes (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, public_id TEXT NOT NULL UNIQUE,
 order_id BIGINT NOT NULL REFERENCES commerce_orders(id) ON DELETE RESTRICT, version BIGINT NOT NULL CHECK(version > 0),
 idempotency_key TEXT NOT NULL UNIQUE, material_snapshot_json TEXT NOT NULL, machine_snapshot_json TEXT NOT NULL,
 file_snapshot_json TEXT NOT NULL, license_snapshot TEXT NOT NULL, tolerance_snapshot_json TEXT NOT NULL,
 finish_snapshot_json TEXT NOT NULL, shipping_snapshot_json TEXT NOT NULL, amount_minor BIGINT NOT NULL CHECK(amount_minor >= 0),
 currency TEXT NOT NULL CHECK(length(currency) = 3), lead_time_days BIGINT NOT NULL CHECK(lead_time_days > 0),
 status TEXT NOT NULL CHECK(status IN ('offered','accepted','rejected','expired')),
 created_by_user_id BIGINT NOT NULL REFERENCES auth_users(id) ON DELETE RESTRICT,
 accepted_by_user_id BIGINT REFERENCES auth_users(id) ON DELETE RESTRICT, accepted_at TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(order_id, version)
);
CREATE TABLE IF NOT EXISTS manufacturing_role_assignments (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL REFERENCES auth_users(id) ON DELETE RESTRICT,
 role TEXT NOT NULL CHECK(role IN ('production_operator','quality_inspector','quality_approver','logistics_operator','safety_manager')),
 active BIGINT NOT NULL DEFAULT 1 CHECK(active IN (0,1)),
 assigned_by_user_id BIGINT NOT NULL REFERENCES auth_users(id) ON DELETE RESTRICT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(user_id, role)
);
CREATE TABLE IF NOT EXISTS manufacturing_resources (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, resource_key TEXT NOT NULL UNIQUE,
 resource_type TEXT NOT NULL CHECK(resource_type IN ('capacity','material')),
 available_units BIGINT NOT NULL CHECK(available_units >= 0), unit TEXT NOT NULL,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS manufacturing_orders (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, public_id TEXT NOT NULL UNIQUE,
 quote_id BIGINT NOT NULL UNIQUE REFERENCES manufacturing_quotes(id) ON DELETE RESTRICT,
 order_id BIGINT NOT NULL UNIQUE REFERENCES commerce_orders(id) ON DELETE RESTRICT,
 state TEXT NOT NULL CHECK(state IN ('reserved','queued','producing','paused','failed','quality_pending','rework','quality_approved','packed','shipped','delivered','cancelled','recalled')),
 assigned_operator_user_id BIGINT REFERENCES auth_users(id) ON DELETE RESTRICT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS manufacturing_reservations (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 manufacturing_order_id BIGINT NOT NULL REFERENCES manufacturing_orders(id) ON DELETE RESTRICT,
 resource_id BIGINT NOT NULL REFERENCES manufacturing_resources(id) ON DELETE RESTRICT,
 units BIGINT NOT NULL CHECK(units > 0), idempotency_key TEXT NOT NULL UNIQUE,
 released_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS manufacturing_events (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 manufacturing_order_id BIGINT NOT NULL REFERENCES manufacturing_orders(id) ON DELETE RESTRICT,
 event_key TEXT NOT NULL UNIQUE, event_type TEXT NOT NULL, from_state TEXT, to_state TEXT NOT NULL,
 reason TEXT NOT NULL DEFAULT '', actor_user_id BIGINT NOT NULL REFERENCES auth_users(id) ON DELETE RESTRICT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS manufacturing_quality_checks (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 manufacturing_order_id BIGINT NOT NULL REFERENCES manufacturing_orders(id) ON DELETE RESTRICT,
 check_key TEXT NOT NULL, specification_json TEXT NOT NULL, measurement_json TEXT,
 result TEXT NOT NULL CHECK(result IN ('pending','passed','failed')), evidence_object_key TEXT,
 inspected_by_user_id BIGINT REFERENCES auth_users(id) ON DELETE RESTRICT,
 approved_by_user_id BIGINT REFERENCES auth_users(id) ON DELETE RESTRICT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(manufacturing_order_id, check_key)
);
CREATE TABLE IF NOT EXISTS manufacturing_shipments (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, public_id TEXT NOT NULL UNIQUE,
 manufacturing_order_id BIGINT NOT NULL UNIQUE REFERENCES manufacturing_orders(id) ON DELETE RESTRICT,
 carrier TEXT NOT NULL, tracking_token_hash TEXT NOT NULL, address_ciphertext TEXT NOT NULL,
 status TEXT NOT NULL CHECK(status IN ('packed','in_transit','exception','delivered','returned')),
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS manufacturing_tracking_events (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 shipment_id BIGINT NOT NULL REFERENCES manufacturing_shipments(id) ON DELETE RESTRICT,
 provider_event_id TEXT NOT NULL, status TEXT NOT NULL, payload_sha256 TEXT NOT NULL,
 occurred_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(shipment_id, provider_event_id)
);
CREATE TABLE IF NOT EXISTS manufacturing_custody_events (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 manufacturing_order_id BIGINT NOT NULL REFERENCES manufacturing_orders(id) ON DELETE RESTRICT,
 event_key TEXT NOT NULL UNIQUE, subject_type TEXT NOT NULL CHECK(subject_type IN ('file','material','part','package')),
 subject_reference_hash TEXT NOT NULL, custody_state TEXT NOT NULL,
 actor_user_id BIGINT NOT NULL REFERENCES auth_users(id) ON DELETE RESTRICT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS manufacturing_incidents (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, public_id TEXT NOT NULL UNIQUE,
 manufacturing_order_id BIGINT NOT NULL REFERENCES manufacturing_orders(id) ON DELETE RESTRICT,
 incident_type TEXT NOT NULL CHECK(incident_type IN ('quality','unsafe_product','logistics','privacy')),
 severity TEXT NOT NULL CHECK(severity IN ('low','medium','high','critical')),
 status TEXT NOT NULL CHECK(status IN ('open','contained','resolved','recalled')),
 evidence_reference_hash TEXT NOT NULL, finance_command_key TEXT UNIQUE,
 created_by_user_id BIGINT NOT NULL REFERENCES auth_users(id) ON DELETE RESTRICT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS manufacturing_recall_items (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 incident_id BIGINT NOT NULL REFERENCES manufacturing_incidents(id) ON DELETE RESTRICT,
 manufacturing_order_id BIGINT NOT NULL REFERENCES manufacturing_orders(id) ON DELETE RESTRICT,
 notification_key TEXT NOT NULL UNIQUE, status TEXT NOT NULL CHECK(status IN ('identified','notified','returned','resolved')),
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(incident_id, manufacturing_order_id)
);

CREATE OR REPLACE FUNCTION printora_manufacturing_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'manufacturing audit record is immutable'; END; $$;
DROP TRIGGER IF EXISTS manufacturing_quotes_no_delete ON manufacturing_quotes;
CREATE TRIGGER manufacturing_quotes_no_delete BEFORE DELETE ON manufacturing_quotes FOR EACH ROW EXECUTE FUNCTION printora_manufacturing_immutable();
DROP TRIGGER IF EXISTS manufacturing_events_no_update ON manufacturing_events;
CREATE TRIGGER manufacturing_events_no_update BEFORE UPDATE OR DELETE ON manufacturing_events FOR EACH ROW EXECUTE FUNCTION printora_manufacturing_immutable();
DROP TRIGGER IF EXISTS manufacturing_custody_no_update ON manufacturing_custody_events;
CREATE TRIGGER manufacturing_custody_no_update BEFORE UPDATE OR DELETE ON manufacturing_custody_events FOR EACH ROW EXECUTE FUNCTION printora_manufacturing_immutable();
