-- Execução privilegiada antes da release que consome o schema.
-- Impacto: DDL aditivo, sem backfill, exclusão ou alteração destrutiva.
-- Validação: repetir em transação, inspecionar constraints e executar testes de concorrência.
-- Rollback: preservar tabelas/dados e restaurar release N-1; não executar DROP ou DELETE.
CREATE TABLE IF NOT EXISTS material_spools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL REFERENCES auth_users(id) ON DELETE RESTRICT,
    material_profile_id BIGINT REFERENCES social_material_profiles(id) ON DELETE SET NULL,
    source TEXT NOT NULL DEFAULT 'local' CHECK(source IN ('local', 'spoolman')),
    external_id TEXT,
    name TEXT NOT NULL,
    material_type TEXT NOT NULL,
    brand TEXT NOT NULL DEFAULT '',
    color_name TEXT NOT NULL DEFAULT '',
    color_hex TEXT,
    lot_code TEXT NOT NULL DEFAULT '',
    initial_weight_g DOUBLE PRECISION CHECK(initial_weight_g IS NULL OR initial_weight_g >= 0),
    remaining_weight_g DOUBLE PRECISION CHECK(remaining_weight_g IS NULL OR remaining_weight_g >= 0),
    location TEXT NOT NULL DEFAULT '',
    storage_state TEXT NOT NULL DEFAULT 'unknown'
        CHECK(storage_state IN ('unknown', 'sealed', 'open', 'drying', 'dry')),
    opened_at TIMESTAMPTZ,
    dried_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    revision BIGINT NOT NULL DEFAULT 1 CHECK(revision > 0),
    status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active', 'archived')),
    last_synced_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK(initial_weight_g IS NULL OR remaining_weight_g IS NULL OR remaining_weight_g <= initial_weight_g),
    UNIQUE(owner_user_id, source, external_id)
);
CREATE INDEX IF NOT EXISTS idx_material_spools_owner_status
ON material_spools(owner_user_id, status, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_material_spools_profile
ON material_spools(material_profile_id, status);

CREATE TABLE IF NOT EXISTS material_consumptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL REFERENCES auth_users(id) ON DELETE RESTRICT,
    spool_id BIGINT NOT NULL REFERENCES material_spools(id) ON DELETE RESTRICT,
    slicing_job_id BIGINT REFERENCES slicing_jobs(id) ON DELETE SET NULL,
    print_history_id BIGINT REFERENCES print_job_history(id) ON DELETE SET NULL,
    idempotency_key TEXT NOT NULL,
    predicted_weight_g DOUBLE PRECISION CHECK(predicted_weight_g IS NULL OR predicted_weight_g >= 0),
    actual_weight_g DOUBLE PRECISION CHECK(actual_weight_g IS NULL OR actual_weight_g >= 0),
    status TEXT NOT NULL CHECK(status IN ('planned', 'confirmed', 'released')),
    remaining_weight_after_g DOUBLE PRECISION CHECK(remaining_weight_after_g IS NULL OR remaining_weight_after_g >= 0),
    note TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmed_at TIMESTAMPTZ,
    released_at TIMESTAMPTZ,
    UNIQUE(owner_user_id, idempotency_key)
);
CREATE INDEX IF NOT EXISTS idx_material_consumptions_spool_created
ON material_consumptions(spool_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_material_consumptions_job
ON material_consumptions(slicing_job_id, print_history_id);

CREATE TABLE IF NOT EXISTS material_quality_samples (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL REFERENCES auth_users(id) ON DELETE RESTRICT,
    spool_id BIGINT NOT NULL REFERENCES material_spools(id) ON DELETE RESTRICT,
    print_history_id BIGINT REFERENCES print_job_history(id) ON DELETE SET NULL,
    sample_type TEXT NOT NULL CHECK(sample_type IN ('dimensional', 'calibration')),
    metric_name TEXT NOT NULL,
    nominal_value_mm DOUBLE PRECISION NOT NULL CHECK(nominal_value_mm >= 0),
    measured_value_mm DOUBLE PRECISION NOT NULL CHECK(measured_value_mm >= 0),
    tolerance_mm DOUBLE PRECISION NOT NULL CHECK(tolerance_mm >= 0),
    result TEXT NOT NULL CHECK(result IN ('passed', 'failed')),
    photo_object_id BIGINT REFERENCES cloud_objects(id) ON DELETE SET NULL,
    note TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_material_quality_spool_created
ON material_quality_samples(spool_id, created_at DESC);

CREATE OR REPLACE FUNCTION printora_material_record_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'material record is immutable'; END; $$;
DROP TRIGGER IF EXISTS material_consumptions_immutable ON material_consumptions;
CREATE TRIGGER material_consumptions_immutable BEFORE UPDATE OR DELETE ON material_consumptions
FOR EACH ROW EXECUTE FUNCTION printora_material_record_immutable();
DROP TRIGGER IF EXISTS material_quality_immutable ON material_quality_samples;
CREATE TRIGGER material_quality_immutable BEFORE UPDATE OR DELETE ON material_quality_samples
FOR EACH ROW EXECUTE FUNCTION printora_material_record_immutable();
