[update_manager mayderprintlab]
type: git_repo
path: /home/pi/MayderPrintLab
origin: https://github.com/mayder/MayderPrintLab.git
primary_branch: main
managed_services: mayderprintlab
install_script: scripts/install_raspberry.sh
