[update_manager printora]
type: git_repo
path: /home/pi/Printora
origin: https://github.com/mayder/printora.git
primary_branch: main
managed_services: printora
install_script: scripts/install_raspberry.sh
